### PR TITLE
Remove Mifis no longer avaliable

### PR DESCRIPTION
**Pull request by Mohmoulay**

### CODE REVIEW

**Review by relet — CHANGES_REQUESTED** [review]
The idea is to remove the entire filtering on apu1d and apu2d. The issue is that we started to build paired nodes from APU1 systems, so you cannot filter on model at all.

**Comment by relet** [comment]
You still need to remove the filter. Please test your code.

**Comment by relet** [comment]
Your latest commit seems to add another copy of monroe.js - is that intended? 
The user interface still seems to add an apu2d filter to requests sent (at least for check availability)

Request URL:https://scheduler.monroe-system.eu/v1/schedules/find?duration=300&interfaceCount=1&nodecount=1&nodetypes=-project:allbesmart%7Cproject:cosmote%7Cproject:flex%7Cproject:membrane%7Cproject:nimbus%7Cproject:nor_lab%7Cproject:roaming%7Cproject:uma,type:deployed,model:apu2d4&start=1516126467

**Comment by Mohmoulay** [comment]
Hi Thomas,
I meant to put that monroe.js in the controller, I believe that it is
related to nodefilters (experiment.disableNodeFilters) as if you check the
function itself still we are using nodemodel= apu2d4, and if I remove that
it will keep picking 257 which isn't even in the user interface.
I tried using one or two interfaces, and it was picking them correctly with
regards to apu2d4. What if we combine apu1d4 and apu2d4 together that way
it can choose apu1d4 ? Anyways I am not an expert by any means.

**Comment by relet** [comment]
257 is a nor_lab node: https://scheduler.monroe-system.eu/v1/resources/257
Is the filter for -project:nor_lab not applied for some reason? Encoding?

**Comment by Mohmoulay** [comment]
I believe so, I will check that tomorrow morning before the teleco, and also contact Miguel because I want to know who did the nodemodelfilter so I don't break the logic.

**Comment by relet** [comment]
You are right, in experiment id 19361 it picked node 257. The filters were

```"-project:allbesmart|project:cosmote|project:flex|project:membrane|project:nimbus|project:nor_lab|project:roaming|project:uma,type:deployed"```

I will check why that is. Still, removing the apu2d filter allows to select these nodes, which is what we want to have.

**Comment by relet** [comment]
The node filter should work correctly now. I fixed some parameter ordering in the backend.

**Comment by Mohmoulay** [comment]
Hi Thomas,
Thank you for your help, Do you want me to modify anything? Or are you pushing this modification. 
Sorry IMDEA is installing some fiber and we have no internet, it will be back shortly.

**Comment by Mohmoulay** [comment]
It's back. I will try it on my local machine before pushing anything!
Thanks!

**Comment by relet** [comment]
I only changed the backend, regarding the nor_lab filter / node 257. You still need to remove the model: filters from the UI code.

**Pull request closed without merging**
